title: "Daniele Cocuzza | AI & Computer Vision Engineer"
description: "Machine Learning, Computer Vision and Deep Learning projects, research and applications."

url: "https://danielecocuzza.github.io"
baseurl: ""

theme: minima

include:
  - assets/video

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

author:
  name: "Daniele Cocuzza"

social_links:
  github: danielecocuzza